### ISSUE TITLE
This is a test

### ISSUE THREAD

**Issue by foobarbaz42** [thomaslevesque/Linq.Extras#1]
For testing email reply

**Comment by thomaslevesque** [comment]
OK, it works

Date: Thu, 14 Jan 2016 13:47:27 -0800

**Comment by thomaslevesque** [comment]
(in case anyone is wondering about this issue, I was trying to understand why email reply from Windows 10 Mail doesn't work. It turns out that the `Reply-To` header is completely ignored, and the app just replies to the sender... :disappointed:)
