### ISSUE TITLE
Nullable attributes for MinBy/MaxBy

### ISSUE THREAD

**Issue by sid-6581** [thomaslevesque/Linq.Extras#17]
It's a little unclear from the documentation what should be returned by `MinBy` and `MaxBy` when given an enumerable of `null` values. The regular LINQ `Min` and `Max` explicitly state that they return `null` in this case, which is very useful because we can use it with `DefaultIfEmpty`.

Should the documentation be more explicit? And if `null` is a valid return value that should probably be annotated with `[return: MaybeNull]`.

**Comment by thomaslevesque** [comment]
Hi @sid-6581,

Interesting question... To be honest, I never really thought about this.

I did a quick test in LinqPad

```csharp
static void Main()
{
	var foos = new[]
	{
		new Foo("hello"),
		new Foo(null),
		new Foo("world"),
	};
	
	foos.MinBy(f => f.Name).Name.Dump();
	foos.Select(f => f.Name).Min().Dump();
}

class Foo
{
	public Foo(string name)
	{
		Name = name;
	}
	
	public string Name { get; }
}
```

This dumps null, then "hello". So the behavior of `MinBy` isn't consistent with Linq's `Min`... I guess this is a bug. `MinBy` should ignore null values, unless there are only null values.

I'm not sure about the `[return: MaybeNull]` attribute, though... If `T` is not nullable, the sequence shouldn't contain nulls, and the method would never return null. And if `T` is nullable, then the attribute is redundant, since we already know that it could be null.

I'll clarify the documentation, though.

Thanks for reporting this!

**Comment by thomaslevesque** [comment]
> I'm not sure about the `[return: MaybeNull]` attribute, though... If `T` is not nullable, the sequence shouldn't contain nulls, and the method would never return null. And if `T` is nullable, then the attribute is redundant, since we already know that it could be null.

Actually, I see that Linq's `Min` has the attribute. Not sure why it's necessary, but I guess they put it there for a reason, so I'll do the same.

**Comment by thomaslevesque** [comment]
Wow. I just realized the behavior of Linq's Min is different for value types and reference types...
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.min?view=netcore-3.1#System_Linq_Enumerable_Min__1_System_Collections_Generic_IEnumerable___0__

> If TSource is a reference type and the source sequence is empty or contains only values that are null, this function returns null.

My implementation always throws if the sequence is empty. I guess I have a few things to review...

**Comment by sid-6581** [comment]
Thanks for looking into it so quickly! As for T not being nullable, it will by default allow nullable unless you restrict it with the `notnull` constraint.

**Comment by thomaslevesque** [comment]
> As for T not being nullable, it will by default allow nullable unless you restrict it with the `notnull` constraint.

Yes, but when you actually call the method with a given `T`, you know whether `T` is nullable or not (and the compiler knows it too). In a nullable context, `Min<string>` or `Min<int>` could never return null, but `Min<string?>` could.

Anyway, I'll add the attribute to remove any ambiguities. I should probably add it to some other methods as well... I'll take my guidance from Linq's code, I guess.

**Comment by sid-6581** [comment]
Now that I am digging into it a little deeper, it seems like LINQ is missing some annotations as well. `DefaultIfEmpty` isn't annotated, so it won't transform a `T` into a `T?`. So `var s = (new string[] { }).DefaultIfEmpty()` looks to be `string`, not `string?`.  In fact, they just use `default!` to shut the compiler up. I'll report that and see what they say about that.

Edit: Actually I don't even know if there is an annotation for this case, where they have two methods instead of just one method with an optional parameter.

**Comment by thomaslevesque** [comment]
@sid-6581 I think I fixed it. I'll make a pass on missing nullability attributes before I make a new release

**Comment by thomaslevesque** [comment]
OK, I don't think there are other `[return: MaybeNull]` attributes missing. The only candidates were the `*OrDefault` methods, but the default value is passed explicitly, so the compiler would warn if it were null for a non-nullable `TSource` anyway.

**Comment by thomaslevesque** [comment]
Technically, this is a breaking change, since it changes the behavior, and could produce warnings that weren't there before.
I should probably release this as a major version. I'll release a beta, could you test it and check that it works as you expect?

**Comment by sid-6581** [comment]
Yes, I can definitely do that! Thanks for getting that done so quickly!

**Comment by thomaslevesque** [comment]
Here it is:
https://github.com/thomaslevesque/Linq.Extras/releases/tag/4.0.0-beta.1
https://www.nuget.org/packages/Linq.Extras/4.0.0-beta.1

**Comment by sid-6581** [comment]
Sorry it took a while to get to it, I was going down the rabbit hole of cleaning a lot of other nullable stuff in my solution. I tried the beta today and that took care of it. Thanks!

**Comment by thomaslevesque** [comment]
No worries, there's no rush!
Thanks for testing, I'll publish 4.0.0 as stable

**Comment by thomaslevesque** [comment]
Done. Thanks again @sid-6581!

**Comment by sid-6581** [comment]
It looks like I spoke too soon. In `ExtremeBy` you are checking if the default for `TKey` is `null`, but if you use `DefaultIfEmpty` in front of `MinBy` or `MaxBy` what will happen is you'll get a collection with one element, where `TSource` is `null`.

If I remove the `DefaultIfEmpty` I would also expect a `null` return, but for the same reason as above it triggers an `EmptySequenceException`.

**Comment by thomaslevesque** [comment]
> It looks like I spoke too soon. In `ExtremeBy` you are checking if the default for `TKey` is `null`, but if you use `DefaultIfEmpty` in front of `MinBy` or `MaxBy` what will happen is you'll get a collection with one element, where `TSource` is `null`.

You mean something like that?

```csharp
items.DefaultIfEmpty().MinBy(item => item.Value)
```
I made a few tests, and the results are consistent with Linq's `Min(Func<TSource, TResult>)`.
If the type of the items is a reference type, it would throw a `NullReferenceException` when accessing `.Value`, but I'd say it's the caller's fault for not taking that into account... 
If it's a value type and `Value` is a reference type, it would return null.
If it's a value type and `Value` is also a value type, it would return the default value for the type of `Value`.

> If I remove the `DefaultIfEmpty` I would also expect a `null` return, but for the same reason as above it triggers an `EmptySequenceException`.

Again, it's the same behavior as Linq

**Comment by thomaslevesque** [comment]
Here's a Gist that shows that it's consistent with Linq:

https://gist.github.com/thomaslevesque/8e0cc655710e8632a59e530348878f78

**Comment by sid-6581** [comment]
You're right, it does appear to be consistent. I totally forgot what I wrote above, that `DefaultIfEmpty()` can't correctly be annotated for nullability with the current annotations. It didn't convert my `TSource` to `TSource?`, so I didn't get a nullability warning on my direct item property access. If I do `item?.Value` it works as expected.

If I do the clunky workaround of writing `DefaultIfEmpty((TSource?)null).MinBy(item => item.Value)` I get the compiler warning I was expecting when referencing `item.Value` improperly, but that's quite ugly and hard to remember. It's just one of those limitations we have to work around currently, I suppose.

Apologies for that!

**Comment by thomaslevesque** [comment]
No problem. Actually I had misunderstood your comment, I thought you were talking about the behavior, not the nullability annotations
